# .gitleaks.toml
title = "lala-infra gitleaks config"

[allowlist]
description = "Ignore generated/third-party content"
paths = [
  '''^cdk\.out/''',
  '''^dist/''',
  '''^node_modules/''',
  '''^tools/''',
  '''^site/assets/icons/''',
]
