name: Secret Scan (Gitleaks)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install gitleaks
        run: |
          set -euo pipefail
          VER="8.24.3"
          curl -sSL "https://github.com/gitleaks/gitleaks/releases/download/v${VER}/gitleaks_${VER}_linux_x64.tar.gz" \
            | tar -xz -C /usr/local/bin gitleaks
          gitleaks version

      - name: Run gitleaks (always write SARIF)
        run: |
          set -euo pipefail
          gitleaks detect \
            --config .gitleaks.toml \
            --redact \
            --report-format sarif \
            --report-path gitleaks.sarif \
            --log-level debug || true

      - name: Upload SARIF to GitHub Security
        if: always() && hashFiles('gitleaks.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
