name: Secret Scan (Gitleaks)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install the CLI
      - name: Install gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          version: latest
        id: install
        # ^ this action just installs the binary to PATH

      # ---- OPTION A: report-only (keeps the check green) ----
      # change --exit-code 0  -> job always succeeds
      # ---- OPTION B: blocking (breaks the build on leaks) ----
      # change --exit-code 1  and REMOVE `continue-on-error: true`
      - name: Run Gitleaks (generate SARIF)
        run: |
          gitleaks detect \
            --source . \
            --report-format sarif \
            --report-path gitleaks.sarif \
            --redact \
            --exit-code 0
        continue-on-error: true

      - name: Upload results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
