name: Secret Scan (Gitleaks)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks (generate SARIF)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact -v --report-format sarif --report-path gitleaks.sarif
        continue-on-error: true  # keep CI green

      - name: Upload results to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
