name: Secret Scan

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # scan full history for PRs

      - name: Install Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          version: latest
          args: detect --source . --no-git --redact --report-format sarif --report-path gitleaks.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
