name: Secret Scan (Gitleaks)

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  security-events: write   # <-- needed so upload-sarif can publish results

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Run gitleaks and OUTPUT SARIF so we can upload it
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          # If you ever add a custom config, set: config-path: .gitleaks.toml
          args: detect --source . --redact --report-format sarif --report-path gitleaks.sarif
        # If you want the repo to pass even when secrets are found, uncomment:
        # continue-on-error: true

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
